# Generated by Django 3.2.11 on 2022-01-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_details_kcno'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('addr', models.CharField(max_length=1000)),
                ('pin', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='designation_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_id', models.IntegerField()),
                ('user2_id', models.IntegerField()),
                ('msg', models.CharField(max_length=1000)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='quotation_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('remarks', models.CharField(max_length=1000)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='quotation_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('q_descp', models.CharField(max_length=1000)),
                ('q_file', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='quotation_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('quotation_id', models.IntegerField()),
                ('remarks', models.CharField(max_length=1000)),
                ('amt', models.FloatField()),
                ('amt_details', models.CharField(max_length=1000)),
                ('plan_file', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='staff_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('desg_id', models.IntegerField()),
                ('addr', models.CharField(max_length=500)),
                ('pin', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
