# Generated by Django 3.2.12 on 2022-04-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_customer_id_quotation_master_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation_reply',
            name='eedt',
            field=models.CharField(default=11, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation_reply',
            name='esdt',
            field=models.CharField(default=11, max_length=20),
            preserve_default=False,
        ),
    ]
