# Generated by Django 3.2.12 on 2022-04-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20220412_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_details',
        ),
    ]
