# Generated by Django 3.2.13 on 2022-05-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=1000)),
            ],
        ),
    ]
